language: python
python:
    - "3.8"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame
install:true
script: python main.py
virtualenv:
    system_site_packages: true